<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test24"
           tests="3"
           failures="1"
           errors="0"
           skipped="2"
           time="0.021">
  <properties />
            <testcase name="setUp" time="0.000" classname="com.test.NewTest">
                <failure type="org.openqa.selenium.remote.UnreachableBrowserException"
                  message="Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &apos;2.53.0&apos;, revision: &apos;35ae25b&apos;, time: &apos;2016-03-15 17:00:58&apos;
System info: host: &apos;DESKTOP-4D3USP3&apos;, ip: &apos;192.168.117.1&apos;, os.name: &apos;Windows 10&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;10.0&apos;, java.version: &apos;1.8.0_101&apos;
Driver info: driver.version: RemoteWebDriver"
              >
<![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.53.0', revision: '35ae25b', time: '2016-03-15 17:00:58'
System info: host: 'DESKTOP-4D3USP3', ip: '192.168.117.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
  com.test.NewTest.setUp(NewTest.java:53)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.TestRunner.beforeRun(TestRunner.java:641)
  org.testng.TestRunner.run(TestRunner.java:609)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 192.168.1.114:5555 [/192.168.1.114] failed: Connection refused: connect
  org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
  org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
  org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
  org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
  org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
  org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
  org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
  org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
  org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
  org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
  org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
  org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
  com.test.NewTest.setUp(NewTest.java:53)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.TestRunner.beforeRun(TestRunner.java:641)
  org.testng.TestRunner.run(TestRunner.java:609)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Connection refused: connect
  java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
  java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
  java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
  java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
  java.net.AbstractPlainSocketImpl.connect(Unknown Source)
  java.net.PlainSocketImpl.connect(Unknown Source)
  java.net.SocksSocketImpl.connect(Unknown Source)
  java.net.Socket.connect(Unknown Source)
  org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
  org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
  org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
  org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
  org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
  org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
  org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
  org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
  org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
  org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
  org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
  org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
  org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
  org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
  org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
  org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
  org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:158)
  com.test.NewTest.setUp(NewTest.java:53)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
  org.testng.TestRunner.beforeRun(TestRunner.java:641)
  org.testng.TestRunner.run(TestRunner.java:609)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
]]>
      </failure>

          </testcase>
  
            <testcase name="afterTest" time="0.0" classname="com.test.NewTest">
          <skipped />
    </testcase>
            <testcase name="f" time="0.0" classname="com.test.NewTest">
          <skipped />
    </testcase>
  
  
</testsuite>
